Output demo.gif

Set FontSize 20
Set Width 1920
Set Height 1080
Set TypingSpeed 0.08

Sleep 0.5s
Type "./claws --demo"
Sleep 1.5s
Enter

Sleep 2s
Type ":"
Sleep 1.5s

Type "vpc/vpcs"
Sleep 1.5s
Enter
Sleep 2s

Type "g"
Sleep 2.5s
Backspace
Sleep 2s
Type "i"
Sleep 2.5s
Backspace
Sleep 2s
Type "j"
Sleep 2s
Enter
Sleep 2s

Type "jjjjjjjj"
Sleep 2.5s
Backspace
Sleep 1.5s
Backspace
Sleep 1.5s
Ctrl+C
Sleep 500ms

